# testbench
lenet_tb.v
sram_model/SRAM_activation_1024x32b.v
sram_model/SRAM_weight_16384x32b.v

# netlist generated by Design Compiler
../syn/netlist/lenet_syn.v
# Logic Gate models
-v /theda21_2/library/GPDK045/cur/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+access+r
